import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import connectDB from '../lib/dbConnect'
import Movie from '../models/Movie'

const Home: NextPage = ({ movies }: any) => {
  
  console.log(movies)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className='container mx-auto'>Movies</h1>
        <Link href={'/new'}>
          <a className="btn btn-primary w-100">Agregar</a>
        </Link>
        {
          movies.map(({ _id, title, plot }: any) => (
            <div className='m-2 card' key={ _id }>
              <div className='card-body'>
                <div className="h5 text-uppercase">{ title }</div>
                <p className="fw-light">{ plot }</p>
                <Link href={`/${_id}`}><a className="m-2 btn btn-success">Más info...</a></Link>
              </div>
            </div>
          ))
        }
      </main>
    </div>
  )
}

export async function getServerSideProps() {
    await connectDB()

    const res = await Movie.find({})

    const movies = res.map(doc => {
      const movie = doc.toObject()
      movie._id = `${movie._id}`
      return movie
    })

    // console.log(res)
    return {props: {movies}}
}

export default Home
